fix compile error in latest Scala 2.13
I think `Arbitrary[scala.collection.mutable.ArraySeq]` should not exists in ScalazArbitrary because it isn't depends on scalaz classes. so make `private[scalaz]`.
This change break source compatibility but keep binary compatibility.

- https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/mutable/ArraySeq.scala
- https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-community-build/1130/consoleFull

```
[scalaz] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.12/project-builds/scalaz-2f8e35c9d2add64fb521f9edf311d106cc56bd45/scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala:271: No ClassTag available for A
[scalaz] [error]   implicit def ArraySeqArbitrary[A: Arbitrary]: Arbitrary[ArraySeq[A]] = Functor[Arbitrary].map(arb[List[A]])(x => ArraySeq(x: _*))
[scalaz] [error]                                                                                                                            ^
[scalaz] [error] /home/jenkins/workspace/scala-2.13.x-integrate-community-build/target-0.9.12/project-builds/scalaz-2f8e35c9d2add64fb521f9edf311d106cc56bd45/scalacheck-binding/src/main/scala/scalaz/scalacheck/ScalazArbitrary.scala:271: No ClassTag available for A
[scalaz] [error]   implicit def ArraySeqArbitrary[A: Arbitrary]: Arbitrary[ArraySeq[A]] = Functor[Arbitrary].map(arb[List[A]])(x => ArraySeq(x: _*))
[scalaz] [error]                                                                                                                            ^
[scalaz] [info] No documentation generated with unsuccessful compiler run
[scalaz] [error] one error found
[scalaz] [error] one error found
[scalaz] [error] (scalacheck-binding_1_14JVM/compile:doc) Scaladoc generation failed
[scalaz] [error] (scalacheck-binding_1_14JVM/compile:compileIncremental) Compilation failed
```